### ISSUE TITLE
DecoderProcessException and multiprocessing?

### ISSUE THREAD

**Issue by spacejake** [sonos/pyFLAC#18]
I am getting an occasional error while using python multiprocessing.  I am unsure if the problem is related to multiprocessing, but I am processing millions of flac files.  I have varified that the audios that are involved in the error seem to load when tried again in a normal single process and multi-process environment, or files that didn't have problem one run may throw this error the next run. So it doesn't seem to be correlated to the files themselves.

Any help would be appriciated, Thank you
# Code to read flac file from in memory buffer
* I use in memory for reading files from web or parse the raw byte header for wav or flac tokens
```python
@dataclass
    class AudioBuffer:
        audio: List[npt.NDArray[Any]] = field(default_factory=list)
        sample_rate: int = 0
        num_channels: int = 0

def _callback(
        audio: npt.NDArray[Any],
        sample_rate: int,
        num_channels: int,
        num_samples: int,
        buffer: AudioBuffer,
    ) -> None:
        buffer.audio.append(audio)
        buffer.sample_rate = sample_rate
        buffer.num_channels = num_channels

def decode(binary: bytes) -> Tuple[npt.NDArray[np.float_], int, int]:
        flac_buffer = FlacDecoder.AudioBuffer()
        flac_decoder = pyflac.StreamDecoder(partial(FlacDecoder._callback, buffer=flac_buffer))

        flac_decoder.process(binary)
        flac_decoder.finish()  # wait until finished processing bytes
        decoded_flac = np.concatenate(flac_buffer.audio).squeeze()
        sample_rate = flac_buffer.sample_rate
        num_channels = flac_buffer.num_channels

        return (
           normalize_if_int(decoded_flac),  # Normlize -1 <= x <=1
            sample_rate,
            num_channels,
        )

    def from_file(file_path: str) -> Tuple[npt.NDArray[np.float_], int, int]:
        with open(file_path, "rb") as fb:
            audio_bytes = fb.read()

        return decode(audio_bytes)
```

# Stack Trace of error
```bash
Traceback (most recent call last):
  File "train_single_pipeline_dist.py", line 1319, in main
    mp.spawn(worker, nprocs=ngpus_per_node, args=(world_size, ngpus_per_node, train, cfg))
  File "/home/conda_user/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/conda_user/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/conda_user/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)

    exec_fn(rank, device_id, device, ngpus_per_node, cfg, training_callbacks)
  File "/share/private/jake/dev/nansy/nansy++/train_single_pipeline_dist.py", line 833, in train
    train_loop(
  File "/share/private/jake/dev/nansy/nansy++/train_single_pipeline_dist.py", line 926, in train_loop
    for step, batch in enumerate(train_loader):
  File "/home/conda_user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/conda_user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1313, in _next_data
    return self._process_data(data)
  File "/home/conda_user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/conda_user/miniconda3/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
pyflac.decoder.DecoderProcessException: Caught DecoderProcessException in DataLoader worker process 7.
Original Traceback (most recent call last):
  File "/home/conda_user/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/conda_user/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/conda_user/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/share/private/jake/dev/nansy/nansy++/dataset/loader.py", line 179, in __getitem__
    audio, spkr, path, voice_type, lang = self._load_sample(idx)
  File "/share/private/jake/dev/nansy/nansy++/dataset/loader.py", line 399, in _load_sample
    audio, _, sr = load_audio(path)
  File "/share/private/jake/dev/nansy/nansy++/dataset/utils.py", line 645, in load_audio
    audio_np, audio_len, sr, _ = load_audio_and_return_format(audio_file)
  File "/share/private/jake/dev/nansy/nansy++/dataset/utils.py", line 595, in load_audio_and_return_format
    audio_np, sr, _ = FlacDecoder()(bytes_data)
  File "/share/private/jake/dev/nansy/nansy++/dataset/utils.py", line 556, in __call__
    flac_decoder.finish()  # wait until finished processing bytes
  File "/home/conda_user/miniconda3/lib/python3.8/site-packages/pyflac/decoder.py", line 231, in finish
    raise DecoderProcessException(self._error)
pyflac.decoder.DecoderProcessException: A fatal read, write, or memory allocation error occurred
```

**Comment by spacejake** [comment]
I switched to using a thread safe queue for my buffer and wait until `not flac_decoder._thread.is_alive()` is finished. This solved my issue
