### ISSUE TITLE
Installation error using Debian Wormbook

### ISSUE THREAD

**Issue by jjorosa** [sonos/pyFLAC#28]
Hi,

I would like to use this library, however I'm having problems to get installed.

I'm using a virtual environment for Python (3.11.2)

The documenation states that for linux distributions we need to execute an additional step. However, the SounFile [link](https://pysoundfile.readthedocs.io/en/latest/#installation)  in the documentation gets a 404 error. 

Anyway, assuming that it was related to the SoundFile library, I tried to install the libsndfile library using

`apt-get install -y libsndfile1`

And it gets installed correctly. But when I try again the pip installation, it fails with the same error:

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyflac
  Using cached pyFLAC-3.0.0.tar.gz (1.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      Traceback (most recent call last):
        File "/opt/webrtc/goog/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/webrtc/goog/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/webrtc/goog/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-4gcx_umb/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-4gcx_umb/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 14, in <module>
        File "/tmp/pip-build-env-4gcx_umb/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-4gcx_umb/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 158, in setup
          dist.parse_config_files()
        File "/tmp/pip-build-env-4gcx_umb/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 632, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/tmp/pip-build-env-4gcx_umb/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 68, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-4gcx_umb/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 104, in read_configuration
          asdict = load_file(filepath) or {}
                   ^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-4gcx_umb/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 33, in load_file
          from ..compat.py310 import tomllib
        File "/tmp/pip-build-env-4gcx_umb/overlay/lib/python3.11/site-packages/setuptools/compat/py310.py", line 8, in <module>
          import tomllib
        File "/usr/lib/python3.11/tomllib/__init__.py", line 7, in <module>
          from ._parser import TOMLDecodeError, load, loads
        File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 936, in exec_module
        File "<frozen importlib._bootstrap_external>", line 1069, in get_code
        File "<frozen importlib._bootstrap_external>", line 729, in _compile_bytecode
      ValueError: bad marshal data (unknown type code)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Probably I'm doing something wrong. Do you have any clues or suggestions that I could use?

Thanks in advance,

**Comment by jjorosa** [comment]
I started with a fresh installation and the problem is no more.

Greetings.
